### ISSUE TITLE
Upload via Piwigo App results in 401

### ISSUE THREAD

**Issue by kaputti1o1** [yonjah/piwigo-privacy#14] opened 2018-10-31 12:10 UTC
Images uploaded by the Piwigo app can not be displayed - it results in a HTTP error 401.

**Comment by yonjah** [comment] 2018-10-31 12:28
Hi @dziemann 
Which Piwigo app ?

Which os, piwigo, plugin and php version are you using ?

Can you please attach a few sample links of urls that work or doesn't work ( You can replace the domain with sample.com and any digit with the digit 1 ) see if there is any obvious difference in their format from thumbnails that due work.

Also check if you have any errors in php error log. You can set piwigo_privacy_debug conf to 1 to get error thrown with the actual reason for the rejection

**Comment by kaputti1o1** [comment] 2018-10-31 14:04
Hi @yonjah 

Thanks for the fast response and please excuse my lazy issue description. Find attached all informations you requested

OS: iOS 12.0
App Version: Piwigo Mobile 2.2.4
PHP: 7.0
pivigo_privacy: 1.0.0

Sample links:

HTTP 200: sample.com/plugins/piwigo_privacy/get.php?img_id=144&file=_data/i/upload/2018/10/31/20181031115541-591bbe06-xx.jpg
HTTP 401: sample.com/plugins/piwigo_privacy/get.php?img_id=131&file=_data/i/upload/2018/10/31/20181031115257-6bafc224-xx.jpg

Both pictures are part of the same album. The first one is uploaded via web and the second via app. Both are in the folder /upload but only the first one is in /_data/i/upload

Is it maybe because I set "deny from all" on i.php?

**Comment by yonjah** [comment] 2018-10-31 14:42
not sure url looks pretty standard.
Can you set the `piwigo_privacy_debug` config to 1 and get the error log ?

**Comment by kaputti1o1** [comment] 2018-10-31 15:45
deactivated the plugin and deleted my htaccess files. Everything is working fine. Activated the plugin again - same error. Activated debug, but where is the logfile written?

**Comment by yonjah** [comment] 2018-11-01 00:43
@dziemann the location of the log depends on your php.ini  `error_log` config.
logs usually go somewhere under `/var/log`
You can check the following guide to see how to enable logs or check you php.ini for their location -
https://www.cyberciti.biz/tips/php-howto-turn-on-error-log-file.html

**Comment by extorn** [comment] 2018-11-01 08:51
Hi,
I'm the android "piwigo client" app developer.

The following pertains to my android app, which isn't necessarily directly relevant, but you could have something similar on the iOS one perhaps?

I had a similar issue with a file I uploaded within the past couple of days. In your app connection settings page, in the "web response caching" section, click on "clear the server response cache".

I don't know why a 500 response would be being cached but it was for me. It is possible that your 401 error is also incorrectly being cached by the app.

There must have been a bug in this plugin at some point because I was looking at the error this morning and it was along the lines of folder is not writeable. No write access within the piwigo_privacy get.php. I just did a couple of uploads this morning though and didn't have the issue. Could the access permissions problem be fixed by a restart (I restarted my piwigo server yesterday before I realised this issue existed).

I can't recall the exact location in the get.php file the error occurred though. Sorry I should have taken a screenshot. If it occurs again I will do.

Here's the error from the website logs

2018/11/01 08:23:11 [error] 1788#1788: *520 FastCGI sent in stderr: "PHP message: PHP Fatal error:  ../../_data/i/./upload/2018/10/27 no write access
#1      mkgetdir /var/www/piwigo/plugins/piwigo_privacy/helper_funcs.inc.php(301)
#2      pwg_privacy_generate_derivative /var/www/piwigo/plugins/piwigo_privacy/helper_funcs.inc.php(235)
#3      pwg_privacy_verify_access /var/www/piwigo/plugins/piwigo_privacy/get.php(63) in /var/www/piwigo/include/functions_html.inc.php on line 403" while reading response header from upstream, client: <client ip>, server: <my server hostname>, request: "GET /piwigo/plugins/piwigo_privacy/get.php?img_id=2831&file=_data/i/upload/2018/10/27/20181027184306-094dc8bf-th.jpg HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "<my server hostname>"

**Comment by yonjah** [comment] 2018-11-01 13:09
hi @extorn 

It seem like php didn't have permission to write to the derivative path.
this might be fixed with a restart if you had php run with a different user.
the code producing the error is mostly copied from piwigo i.php so unless it's trying to access
the wrong path I would imagine piwigo will fail to handle derivative even when piwigo_privacy is disabled.

If you do see this issue happening again it might be worth opening another issue so we can try track it down.

Thank's for mentioning the cache issue. I assume @dziemann tried to access the images from his browser and not directly from the app (since he supplied the url) but if not it might be a good point to first make sure accessing the website directly reproduces this issue.

**Comment by kaputti1o1** [comment] 2018-11-05 08:29
Hi together,

thank you all for the investigation and your support. Sorry, for my late response on the topic, but I solved the problem in another way. I uninstalled the plugin and installed it again. Additionally I deleted all .htaccess files even if they where empty. After verifying the correct function I created the .htaccess files one by one and tested after each creation. Now it works fine! Maybe really only a cache issue.

**Closed as completed** 2018-11-05 08:29 UTC
